---
- name: Pull war
  hosts: ansi
  become: true
  tasks:
    - name: Pull war
      get_url: 
        url: "http://13.127.86.90:8081/repository/Anshu/in/javahome/simpleapp/6.0.0/simpleapp-6.0.0.war"
        dest: ./
        url_username: admin
        url_password: admin
...       
