---
- name: Tomcat Deployment
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    URL_TOM: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.zip"
    URL_TOMZIP: "{{ URL_TOM.split('/') | last }}"
  tasks:
    - name: Download tomcat 8
      get_url:
        url: "{{ URL_TOM }}"
        dest: ./
    - name: Extract tomcat to /opt
      unarchive:
        src: ./{{ URL_TOMZIP }}
        dest: ./
        remote_src: true
    - name: Pull war
      get_url: 
        url: "http://13.127.86.90:8081/repository/Anshu/in/javahome/simpleapp/6.0.0/simpleapp-6.0.0.war"
        dest: ./
        url_username: admin
        url_password: admin
    - name: Upload Artifact to Tomcat
      copy:
        src: ./simpleapp-6.0.0.war
        dest: ./apache-tomcat-8.5.83/webapps/
        remote_src: true
    - name: Start Tomcat
      shell: "sh ./apache-tomcat-8.5.83/bin/catalina.sh start"
...

