---
- name: Tomcat Deployment
  hosts: all
  become: true
  vars:
    URL_ART: "http://13.126.139.109/repository/Anshu/in/javahome/simpleapp/6.0.0/simpleapp-6.0.0.war"
    URL_TOM: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.zip"
    URL_TOMZIP: "{{ URL_TOM.split('/') | last }}"
  tasks:
    - name: Download tomcat 8
      get_url:
        url: "{{URL_TOM}}"
        dest: /opt/
    - name: Extract tomcat to /opt
      unarchive:
        src: /opt/{{ URL_TOMZIP }}
        dest: /opt/
        remote_src: true
    - name: Download Artifact
      get_url:
        url: "{{URL_ART}}"
        dest: /opt/apache-tomcat-8.5.83/webapps/
    - name: Start Catalina
      shell: "sh ./apache-tomcat-8.5.83/bin/catalina.sh start"
...

