---
- name: Tomcat Deployment
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    URL_TOM: "https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.zip"
    URL_TOMZIP: "{{ URL_TOM.split('/') | last }}"
  tasks:
    - name: Download tomcat 8
      get_url:
        url: "{{ URL_TOM }}"
        dest: ./
    - name: Extract tomcat to /
      unarchive:
        src: ./{{ URL_TOMZIP }}
        dest: ./
        remote_src: true      
    - name: Upload Artifact to Tomcat
      copy:
        src: /home/ec2-user/workspace/demo/simpleapp-6.0.0.war.*
        dest: ./apache-tomcat-8.5.83/webapps/
        remote_src: true
    - name: Start Tomcat
      shell: "sh ./apache-tomcat-8.5.83/bin/catalina.sh start"
...

